### ISSUE TITLE
Biome checklist

### ISSUE THREAD

**Issue by Lykrast** [Lykrast/MysticalWildlife#2]
A list of vanilla biomes where I intend to add mobs to, as well as how many are currently added:

- [x] Tundra : 1 (Wintry Cicaptera)
- [x] Mountains : 1 (Vrontausaurus)
- [ ] Taiga : 0
- [x] Plains : 1 (Azure Cicaptera)
- [x] Forest : 2 (Verdant Cicaptera, Dusk Lurker)
- [x] Dark Forest : 1 (Dusk Lurker)
- [x] Swamp : 1 (Yaga Hog)
- [ ] Jungle : 0
- [ ] River : 0
- [x] Beach : 2 (Plumper, Krill)
- [ ] Mushroom Fields : 0
- [ ] The End : 0
- [x] Desert : 2 (Sandy Cicaptera, Crimson Cicaptera)
- [ ] Savanna : 0
- [ ] The Nether : 0
- [ ] Ocean : 0
